### ISSUE TITLE
Unable to create ~/.ros/camera_info

### ISSUE THREAD

**Issue by neurodisk23** [heethesh/auro_calibration#39]
The additional window is being generated and I have the following on my command line 

harshal@harshal:~/ros_workspace$ roslaunch lidar_camera_calibration camera_calibration.launch
... logging to /home/harshal/.ros/log/18318052-2021-11ec-acdf-1866da13cbd1/roslaunch-harshal-7870.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://harshal:45381/

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.11

NODES
  /
    cameracalibrator (camera_calibration/cameracalibrator.py)
    player (rosbag/play)

auto-starting new master
process[master]: started with pid [7883]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 18318052-2021-11ec-acdf-1866da13cbd1
process[rosout-1]: started with pid [7897]
started core service [/rosout]
process[player-2]: started with pid [7901]
[ INFO] [1632808706.025936631]: Opening /home/harshal/ros_workspace/src/lidar_camera_calibration/bagfiles/file.bag

Waiting 0.2 seconds after advertising topics...process[cameracalibrator-3]: started with pid [7910]
 done.

Hit space to toggle paused, or 's' to step.
Saved screen dump to /tmp/dump0.png2925   Duration: 0.157125 / 4.902407               **37.22** 
Saved screen dump to /tmp/dump1.png3139   Duration: 0.967339 / 4.902407               
Saved screen dump to /tmp/dump2.png5302   Duration: 1.199502 / 4.902407               
Saved screen dump to /tmp/dump3.png8807   Duration: 1.443007 / 4.902407               
[player-2] killing on exit690473.726986   Duration: 4.701186 / 4.902407               
[cameracalibrator-3] killing on exit
 [RUNNING]  Bag Time: 1631690473.847773   Duration: 4.821973 / 4.902407               
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

If anyone can help as to why the .ros/camera_info is not generating and what does the 37.2 number indicates

**Comment by heethesh** [comment]
please create an issue with ROS `camera_calibration` package, this is not related to the lidar calibration package

**Comment by neurodisk23** [comment]
Okay, Thankyou for your response
