### ISSUE TITLE
Camera calibration is not working, giving curved images while playing the updated rosbag file ( using cameracalibrator.py for getting the parameters).)

### ISSUE THREAD

**Issue by neurodisk23** [heethesh/auro_calibration#44]
Dear sir, 
            I am facing an issue regarding the camera calibration, the command to generate the parameter in the repo is not working on our system so we got the ost.yml file and the images from the ros cameracalibrator.py [here is the link](http://wiki.ros.org/camera_calibration), I have attached a google doc file with all the steps and methods we follow, please look into it and it'd be really helpful if you could provide us with your valuable suggestions as to where are we getting it wrong.

google doc: https://drive.google.com/file/d/1xHIiCQy1X_ZurqnUTnDtCl0UAr84VXSV/view?usp=sharing

Thanks and regards
Harshal

**Comment by arjunskumar** [comment]
@neurodisk23 are you able to solve ?
