### ISSUE TITLE
Error after picking points

### ISSUE THREAD

**Issue by aristow1** [heethesh/auro_calibration#51]
after i picked all of the points on both the 3D Gui and the 2 GUI i recieve this warning and i dont understand what it actually means.

INFO] [1666878540.478949]: PCL points available: 3130
[INFO] [1666878575.289837]: PCL: (2.2614870071411133, 0.4740966558456421, 0.28371185064315796)
[INFO] [1666878576.479389]: PCL: (2.2876789569854736, -0.3521074950695038, 0.2841993272304535)
[INFO] [1666878579.799804]: PCL: (2.3190083503723145, -0.3573438823223114, -0.28809913992881775)
[INFO] [1666878584.135509]: PCL: (2.284597158432007, 0.470207154750824, -0.2863929867744446)
[INFO] [1666878586.390756]: PCL: (2.2614870071411133, 0.4740966558456421, 0.28371185064315796)
[INFO] [1666878595.153496]: IMG: (572.2272727272727, 380.66883116883116)
[INFO] [1666878602.846029]: IMG: (1055.9935064935066, 374.17532467532465)
[INFO] [1666878605.141449]: IMG: (1059.2402597402597, 708.5909090909091)
[INFO] [1666878607.957493]: IMG: (578.7207792207793, 724.8246753246754)
[INFO] [1666878611.813398]: IMG: (572.2272727272727, 390.4090909090909)
[WARN] [1666878620.271324]: PnP RANSAC Requires minimum 5 points
Press [ENTER] to pause and pick points

anyhelp please ????

**Comment by dptmf35** [comment]
how did you solve this prbolem? I got same problem
