### ISSUE TITLE
error

### ISSUE THREAD

**Issue by farhad-dalirani** [heethesh/auro_calibration#61]
Hello,
I face this error:

src/lidar_camera_calibration/scripts/calibrate_camera_lidar.py", line 340, in calibrate
    rmse = np.sqrt(np.mean(error[:, 0] ** 2 + error[:, 1] ** 2))
IndexError: index 1 is out of bounds for axis 1 with size 1

**Comment by ppwwwww** [comment]
<340 line & 358 line > 

   error = np.reshape(error, (-1, 2))    # <-- add !!!!!!!!!
   rmse = np.sqrt(np.mean(error[:, 0] ** 2 + error[:, 1] ** 2))
